= mpv scripts by Arjun Satarkar
:toc:

Assume these are compatible only with Unix-like systems by default; examination of the code will often suggest relatively minor modifications needed to support Windows. If this is relevant to your use case, feel free to open an issue or pull request.

== Scripts

* *mpvclip.* Clip sections of video with ffmpeg. Allows choosing CRF/two-pass target size, with sensible defaults.
* *get_subtitle.* Copy the text of the current subtitle line to the clipboard. Relies on `https://github.com/astrand/xclip[+xclip+`] to function.
* *savepoints.* Save the current video timestamp to disk, and easily jump between all savepoints set for a particular video.

== Copying

....
mpv scripts
Copyright (C) 2025-present Arjun Satarkar

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License version 3.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the GNU General Public License version 3 for
more details.
....

The file `+LICENSE.txt+` in this directory contains the text of the license.
