= mpv scripts by Arjun Satarkar
:toc:

Assume these are compatible only with Unix-like systems by default; examination of the code will often suggest relatively minor modifications needed to support Windows. If this is relevant to your use case, feel free to open an issue or pull request.

== Scripts

=== mpvclip

Clip sections of video with ffmpeg. Allows choosing CRF/two-pass target size, with sensible defaults.

*Key binding*: `+clip-ab+`, by default mapped to `+c+`.

=== get_subtitle

Copy the text of the current subtitle line to the clipboard *or* open it in the browser (useful for integration with eg. https://yomitan.wiki/[Yomitan]).

The clipboard part relies on https://github.com/astrand/xclip[`+xclip+`] to function. Opening in the browser uses `+xdg-open+`.

*Key bindings*:

- `+copy-subtitle+`, by default mapped to `+g+`.
- `+open-subtitle-in-browser+`, by default mapped to `+ctrl+g+`.

=== savepoints

Save the current video timestamp to disk, and easily jump between all savepoints set for a particular video.

*Key bindings*:

- `+add-savepoint+`, by default mapped to `+a+`.
- `+jump-to-savepoint+`, by default mapped to `+ctrl+a+`.

== Copying

....
mpv scripts
Copyright (C) 2025-present Arjun Satarkar

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License version 3.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the GNU General Public License version 3 for
more details.
....

The file `+LICENSE.txt+` in this directory contains the text of the license.
